SET SERVEROUTPUT ON

DECLARE 
      NUM NUMBER; 
BEGIN 
      SELECT COUNT(1) INTO NUM FROM USER_TABLES WHERE TABLE_NAME = 'CCY_REGION_HOLIDAY'; 
      IF 1 = NUM THEN 
          EXECUTE IMMEDIATE 'DROP TABLE CCY_REGION_HOLIDAY';
      END IF; 
END; 
/

DECLARE 
      NUM NUMBER; 
BEGIN 
      SELECT COUNT(1) INTO NUM FROM USER_OBJECTS WHERE OBJECT_NAME = 'SEQ_CCY_REGION_HOLIDAY' AND OBJECT_TYPE = 'SEQUENCE'; 
      IF 1 = NUM THEN 
          EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CCY_REGION_HOLIDAY';
      END IF; 
END; 
/

CREATE TABLE CCY_REGION_HOLIDAY(
    ID 					NUMBER 			 		    NOT NULL PRIMARY KEY,
    CURRENCY 			NVARCHAR2(3)	 			NOT NULL,
    REGION 				NVARCHAR2(100)    			NOT NULL,
    HOLIDAY_DATE    	DATE						NOT NULL,
    LOCK_FLAG       	NUMBER(1)                   NOT NULL,
    HOLIDAY_TYPE    	NVARCHAR2(1)				NOT NULL,
    CREATION_TIME 		TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATION_STAFFID 	NVARCHAR2(50)				NOT NULL,
    MODIFIED_TIME 		TIMESTAMP WITH TIME ZONE NOT NULL,
    MODIFIED_STAFFID 	NVARCHAR2(50)				NOT NULL
);

CREATE SEQUENCE SEQ_CCY_REGION_HOLIDAY  
MINVALUE 1
MAXVALUE 9999999
START WITH 1
INCREMENT BY 1
NOCACHE
ORDER;


CREATE OR REPLACE TRIGGER TG_CCY_REGION_HOLIDAY_INS
BEFORE INSERT ON CCY_REGION_HOLIDAY
FOR EACH ROW
BEGIN
  SELECT SYSTIMESTAMP INTO :NEW.CREATION_TIME FROM DUAL;
  SELECT SYSTIMESTAMP INTO :NEW.MODIFIED_TIME FROM DUAL;
END;
/

alter table CCY_REGION_HOLIDAY add constraint CCY_REGION_HOLIDAY_CST1 unique (CURRENCY, REGION, HOLIDAY_DATE);