server:
  port: 8081
  servlet:
    context-path: /girl

cupSize: B
age: 18

content: "cupSize: ${cupSize}, age: ${age}"

girl:
  age: 19
  cupSize: C


spring:
 thymeleaf:
   cache: false
   suffix: .jsp
   encoding: UTF-8
   mode: HTML5
