CREATE OR REPLACE PROCEDURE USP_DEL_MONTHLY_HOLIDAY( V_CURRENCY IN NVARCHAR2,
													   V_REGION IN NVARCHAR2,
													   V_DATE_HEAD IN DATE,
													   V_DATE_TAIL IN DATE,
													   V_ERR_CODE OUT NUMBER
													   )
													   
AS

BEGIN	
		V_ERR_CODE := 0;
		DELETE FROM CCY_REGION_HOLIDAY WHERE CURRENCY = V_CURRENCY
										AND    REGION = V_REGION
										AND    HOLIDAY_DATE >= V_DATE_HEAD
										AND    HOLIDAY_DATE <= V_DATE_TAIL;
		
	
	
EXCEPTION
	WHEN OTHERS THEN
		V_ERR_CODE := -1;	
END;
/